"""Add users and bots tables

Revision ID: 65f8715d7bcf
Revises: 93d0a523a218
Create Date: 2024-09-15 14:42:26.444391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f8715d7bcf'
down_revision = '93d0a523a218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('tg_bot_token', sa.String(), nullable=True),
    sa.Column('turcode_login', sa.String(), nullable=True),
    sa.Column('turcode_pass', sa.String(), nullable=True),
    sa.Column('auth_cookie', sa.String(), nullable=True),
    sa.Column('claimed_payouts_limit', sa.Integer(), nullable=False),
    sa.Column('claimed_payouts_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('user_bot_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bot_association')
    op.drop_table('users')
    op.drop_table('bots')
    # ### end Alembic commands ###
