"""Add fields to payouts table

Revision ID: 6c8eafee73b9
Revises: 78421985b5cd
Create Date: 2024-08-10 19:22:42.982335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8eafee73b9'
down_revision = '78421985b5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('payouts', sa.Column('card', sa.String(), nullable=True))
    op.add_column('payouts', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('payouts', sa.Column('payout_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'payout_id')
    op.drop_column('payouts', 'phone')
    op.drop_column('payouts', 'card')
    op.drop_column('payouts', 'bank_name')
    # ### end Alembic commands ###
