"""Add bot_name to payouts table

Revision ID: 78421985b5cd
Revises: 
Create Date: 2024-08-05 11:01:38.509509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78421985b5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('bot_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'bot_name')
    # ### end Alembic commands ###
