"""Add payouts table

Revision ID: 93d0a523a218
Revises: 
Create Date: 2024-09-14 17:28:29.145466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d0a523a218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('card', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('payout_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    # ### end Alembic commands ###
