"""Add field to payout

Revision ID: a82f12a0ba82
Revises: 65f8715d7bcf
Create Date: 2024-09-19 10:46:19.406169

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a82f12a0ba82'
down_revision = '65f8715d7bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('is_gained_and_notified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'is_gained_and_notified')
    # ### end Alembic commands ###
